### ISSUE TITLE
Generate metadata for DSRA datasets

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/downloads#3]
We need to have metadata for the DSRA datasets prior to sending them to FGP.

Template here: https://github.com/OpenDRR/data/blob/main/metadata/Metadata_Minimum_Partner_Information_Form_v2.xlsx

@jvanulde to handle the translation.

**Comment by tieganh** [comment]
Hey @jvanulde are you taking a first crack at this or should i?

**Comment by jvanulde** [comment]
Yes, I am handling this. When the FGP is back up please review the metadata records in the collection. Once you approve I'll submit for publishing approval (via Director).

**Comment by tieganh** [comment]
That’s great, Joost, thank you! If you see that the site is back up feel free to send me a push.




—
Tiegan Hobbs, PhD, MSCE
Seismic Risk Scientist | Geological Survey of Canada
Adjunct Professor | University of British Columbia
www.tieganhobbs.com
+1 (236) 330-2180

Working on the traditional and unceded territory of the Coast Salish Peoples.

On Dec 16, 2021, at 11:15 AM, Joost van Ulden ***@***.***> wrote:

﻿

Yes, I am handling this. When the FGP is back up please review the metadata records in the collection. Once you approve I'll submit for publishing approval (via Director).

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenDRR%2Fdownloads%2Fissues%2F3%23issuecomment-995965195&data=04%7C01%7Ctiegan.hobbs%40NRCan-RNCan.gc.ca%7C635f37a03f84463124e008d9c0af377c%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637752681054754483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Paau6198HNyxdTR3O1Q7mmIdvt665AuiO5%2B%2BBXn9h24%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOHGWE7PGDNWCM26CBPIE4DURIGALANCNFSM5KBQ2R2Q&data=04%7C01%7Ctiegan.hobbs%40NRCan-RNCan.gc.ca%7C635f37a03f84463124e008d9c0af377c%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637752681054754483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dx2TfPtYymvZz7FbmAYCECFSoM1%2F7wOq6Oc%2BidC8Fvg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctiegan.hobbs%40NRCan-RNCan.gc.ca%7C635f37a03f84463124e008d9c0af377c%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637752681054754483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iAUyShXnFAzd%2F5m15IjFTxo2r5O80tQaUoplFVDIP1M%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctiegan.hobbs%40NRCan-RNCan.gc.ca%7C635f37a03f84463124e008d9c0af377c%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637752681054754483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q%2BE5hevHKQSanaUZmNuedzrDSABq0eGfdsUtNfnE3p4%3D&reserved=0>.

**Comment by jvanulde** [comment]
Metadata is complete. Waiting on MXD files to be completed prior to publishing.
